[package]
name = "pkg-cli"
description = "CLI tool for Halo Wars 2 PKG archives"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[[bin]]
name = "pkg"
path = "src/main.rs"

[dependencies]
pkg = { workspace = true, features = ["std"] }
clap.workspace = true
serde.workspace = true
serde_json.workspace = true
glob = "0.3.3"
