[package]
name = "fxb-cli"
description = "Command-line tool for FXB (HWDE compiled shader) files"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[lints]
workspace = true

[[bin]]
name = "fxb"
path = "src/main.rs"
doc = false

[dependencies]
fxb = { workspace = true }
d3dasm = { workspace = true }
clap = { workspace = true }
