[workspace]
resolver = "3"
members = [
    "crates/bdt",
    "crates/ddx",
    "crates/ecf",
    "crates/era",
    "crates/uax",
    "crates/xml",
    "crates/xmb",
    "crates/ugx",
    "crates/ugx-gltf",
    "crates/xtd",
    "crates/xtt",
    "crates/era-cli",
    "crates/xmb-cli",
    "crates/ugx-cli",

    "crates/pkg",
    "crates/pkg-cli",
    "crates/bdt-serde",
    "crates/xmb-serde",
    "crates/test-utils",
    "crates/uax-cli",
    "crates/ufx",
    "crates/ufx-cli",
    "crates/fxb",
    "crates/fxb-cli",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"
repository = "https://github.com/coconutbird/ensemble-formats"
authors = ["coconutbird"]

[workspace.dependencies]
# Internal dependencies
bdt = { path = "crates/bdt" }
bdt-serde = { path = "crates/bdt-serde" }
ddx = { path = "crates/ddx" }
ecf = { path = "crates/ecf" }
era = { path = "crates/era" }
uax = { path = "crates/uax" }
xmb = { path = "crates/xmb" }
xmb-serde = { path = "crates/xmb-serde" }
ugx = { path = "crates/ugx" }
ugx-gltf = { path = "crates/ugx-gltf" }
test-utils = { path = "crates/test-utils" }
xtd = { path = "crates/xtd" }
xml = { path = "crates/xml" }
xtt = { path = "crates/xtt" }
ugx-cli = { path = "crates/ugx-cli" }
pkg = { path = "crates/pkg" }
ufx = { path = "crates/ufx" }
ufx-cli = { path = "crates/ufx-cli" }
fxb = { path = "crates/fxb" }
fxb-cli = { path = "crates/fxb-cli" }

# External dependencies
base64 = "0.22"
hashbrown = { version = "0.16.1", default-features = false, features = [
    "default-hasher",
    "alloc",
] }
cfglib = { git = "https://github.com/coconutbird/cfglib.git", branch = "dev/il" }
d3dasm = { git = "https://github.com/coconutbird/d3dasm.git", branch = "main" }
texture2ddecoder = "0.1"
flate2 = "1.0"
glob = "0.3.3"
gltf = "1.4"
gltf-json = { version = "1.4", features = ["names", "extras"] }
hex = "0.4.3"
thiserror = "2.0"
sha1 = { version = "0.10", default-features = false }
tiger = { version = "0.2", default-features = false }
clap = { version = "4.5", features = ["derive"] }
quick-xml = "0.37"
xmlparser = { version = "0.13", default-features = false }
half = "2.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rayon = "1.10"
image = "0.25"
miniz_oxide = { version = "0.8", default-features = false, features = [
    "with-alloc",
] }
nostdio = "0.2"
num-traits = { version = "0.2", default-features = false }
zerocopy = { version = "0.8", features = ["derive"] }
dotenvy = "0.15"

[workspace.lints.rust]
warnings = { level = "deny", priority = -2 }
unused = { level = "deny", priority = -1 }
nonstandard_style = { level = "deny", priority = -1 }
rust_2018_idioms = { level = "deny", priority = -1 }
future_incompatible = { level = "deny", priority = -1 }

[workspace.lints.clippy]
correctness = { level = "deny", priority = -1 }
suspicious = { level = "deny", priority = -1 }
style = { level = "deny", priority = -1 }
complexity = { level = "deny", priority = -1 }
perf = { level = "deny", priority = -1 }
pedantic = { level = "deny", priority = -1 }

[workspace.lints.rustdoc]
all = { level = "deny", priority = -1 }
