[workspace]
resolver = "3"
members = [
    "crates/bdt",
    "crates/ddx",
    "crates/ecf",
    "crates/era",
    "crates/uax",
    "crates/xml",
    "crates/xmb",
    "crates/ugx",
    "crates/ugx-gltf",
    "crates/xtd",
    "crates/xtt",
    "crates/era-cli",
    "crates/xmb-cli",
    "crates/ugx-cli",

    "crates/pkg",
    "crates/pkg-cli",
    "crates/bdt-serde",
    "crates/xmb-serde",
    "crates/test-utils",
    "crates/ufx",
    "crates/ufx-cli",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"
repository = "https://github.com/coconutbird/ensemble-formats"
authors = ["coconutbird"]

[workspace.dependencies]
# Internal dependencies
bdt = { path = "crates/bdt" }
bdt-serde = { path = "crates/bdt-serde" }
ddx = { path = "crates/ddx" }
ecf = { path = "crates/ecf" }
nostdio = "0.1"
era = { path = "crates/era" }
uax = { path = "crates/uax" }
xmb = { path = "crates/xmb" }
xmb-serde = { path = "crates/xmb-serde" }
ugx = { path = "crates/ugx" }
ugx-gltf = { path = "crates/ugx-gltf" }
test-utils = { path = "crates/test-utils" }
xtd = { path = "crates/xtd" }
xml = { path = "crates/xml" }
xtt = { path = "crates/xtt" }
ugx-cli = { path = "crates/ugx-cli" }
pkg = { path = "crates/pkg" }
ufx = { path = "crates/ufx" }
ufx-cli = { path = "crates/ufx-cli" }

# External dependencies
cfglib = { git = "https://github.com/coconutbird/cfglib.git" }
cfglib-dxbc = { git = "https://github.com/coconutbird/cfglib.git" }
d3dasm = { version = "0.1" }
byteorder = "1.5"
texture2ddecoder = "0.1"
flate2 = "1.0"
thiserror = "2.0"
sha1 = { version = "0.10", default-features = false }
tiger = { version = "0.2", default-features = false }
clap = { version = "4.5", features = ["derive"] }
quick-xml = "0.37"
xmlparser = { version = "0.13", default-features = false }
half = "2.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rayon = "1.10"
image = "0.25"
zerocopy = { version = "0.8", features = ["derive"] }
dotenvy = "0.15"


[patch.crates-io]
dxbc = { git = "https://github.com/coconutbird/d3dasm.git" }
