[package]
name = "ddx"
description = "DDX texture format parser for Halo Wars"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
ecf = { workspace = true }
thiserror = { workspace = true }
miniz_oxide.workspace = true
nostdio.workspace = true
texture2ddecoder.workspace = true
zerocopy.workspace = true

[dev-dependencies]
era = { workspace = true }
