[package]
name = "ddx"
description = "DDX texture format parser for Halo Wars"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
ecf = { workspace = true }
byteorder = { workspace = true }
thiserror = { workspace = true }
flate2 = { workspace = true }

[dev-dependencies]
era = { workspace = true }

