[package]
name = "xtt"
description = "XTT terrain texture format parser for Halo Wars"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
ecf = { workspace = true }
thiserror = { workspace = true }
texture2ddecoder = { workspace = true }
half.workspace = true
zerocopy.workspace = true

[dev-dependencies]
era = { workspace = true }
image = { workspace = true }
