//! Build script for the `ugx` crate.
//!
//! Reads `src/data/hogan_perm_sets.json` and generates Rust static arrays
//! for shader permutation sets and their texture requirements. This keeps
//! the JSON as the single source of truth while producing `no_std`-compatible
//! code with zero runtime parsing.

use std::collections::HashMap;
use std::env;
use std::fs;
use std::path::Path;

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let json_path = Path::new(&manifest_dir).join("src/data/hogan_perm_sets.json");

    println!("cargo::rerun-if-changed={}", json_path.display());

    let json_str = fs::read_to_string(&json_path)
        .unwrap_or_else(|e| panic!("failed to read {}: {e}", json_path.display()));

    let data: HashMap<String, Vec<PermSetJson>> = parse_json(&json_str);

    let out_dir = env::var("OUT_DIR").unwrap();
    let out_path = Path::new(&out_dir).join("hogan_perm_data.rs");

    let mut code = String::new();
    code.push_str("// Auto-generated by build.rs from src/data/hogan_perm_sets.json\n");
    code.push_str("// DO NOT EDIT — regenerate by modifying the JSON and rebuilding.\n\n");

    for family in &["hogan_standard", "hogan_decal", "hogan_water"] {
        let upper = family.to_uppercase();
        if let Some(sets) = data.get(*family) {
            // Perm sets array
            code.push_str(&format!(
                "/// Permutation sets for `{upper}`, ordered by frequency.\n"
            ));
            code.push_str(&format!(
                "#[allow(dead_code)]\npub static {upper}_PERM_SETS: &[&[PermEntry]] = &[\n"
            ));
            for s in sets {
                code.push_str(&format!("    // count={}\n    &[", s.count));
                for (j, p) in s.perms.iter().enumerate() {
                    if j > 0 {
                        code.push_str(", ");
                    }
                    code.push_str(&format!("(\"{upper}_{}\", 0x{:08X})", p.bitmask, p.hash));
                }
                code.push_str("],\n");
            }
            code.push_str("];\n\n");

            // Texture metadata array
            code.push_str(&format!(
                "/// Texture slots required by each `{upper}_PERM_SETS` entry.\n"
            ));
            code.push_str(&format!(
                "#[allow(dead_code)]\nstatic {upper}_PERM_TEXTURES: &[&[&str]] = &[\n"
            ));
            for (i, s) in sets.iter().enumerate() {
                code.push_str(&format!("    // [{i}] count={}\n    &[", s.count));
                for (j, t) in s.textures.iter().enumerate() {
                    if j > 0 {
                        code.push_str(", ");
                    }
                    code.push_str(&format!("\"{t}\""));
                }
                code.push_str("],\n");
            }
            code.push_str("];\n\n");
        }
    }

    fs::write(&out_path, &code)
        .unwrap_or_else(|e| panic!("failed to write {}: {e}", out_path.display()));
}

// Minimal JSON parsing without serde (build scripts can use std but we avoid
// adding serde as a build-dependency).

#[derive(Debug)]
struct PermSetJson {
    count: u32,
    textures: Vec<String>,
    perms: Vec<PermJson>,
}

#[derive(Debug)]
struct PermJson {
    bitmask: String,
    hash: u32,
}

fn parse_json(s: &str) -> HashMap<String, Vec<PermSetJson>> {
    // Very simple state-machine JSON parser for our known schema.
    // We only need to handle: { "family": [ { count, textures: [...], perms: [{ bitmask, hash }] } ] }
    let mut result = HashMap::new();

    // Find each top-level key
    let mut pos = 0;
    while let Some(key_start) = s[pos..].find('"') {
        let abs_start = pos + key_start + 1;
        let key_end = s[abs_start..].find('"').unwrap() + abs_start;
        let family = &s[abs_start..key_end];

        // Find the opening [ for this family's array
        pos = key_end + 1;
        let arr_start = s[pos..].find('[').unwrap() + pos;
        let arr_end = find_matching_bracket(s, arr_start);

        let sets = parse_perm_sets(&s[arr_start..=arr_end]);
        result.insert(family.to_string(), sets);

        pos = arr_end + 1;
        // Skip to next key or end
        if s[pos..].find('"').is_none() {
            break;
        }
    }
    result
}

fn find_matching_bracket(s: &str, open: usize) -> usize {
    let open_ch = s.as_bytes()[open];
    let close_ch = match open_ch {
        b'[' => b']',
        b'{' => b'}',
        _ => panic!("not a bracket at pos {open}"),
    };
    let mut depth = 1i32;
    let mut i = open + 1;
    let bytes = s.as_bytes();
    while i < bytes.len() {
        match bytes[i] {
            b'"' => {
                i += 1;
                while i < bytes.len() && bytes[i] != b'"' {
                    if bytes[i] == b'\\' {
                        i += 1;
                    }
                    i += 1;
                }
            }
            c if c == open_ch => depth += 1,
            c if c == close_ch => {
                depth -= 1;
                if depth == 0 {
                    return i;
                }
            }
            _ => {}
        }
        i += 1;
    }
    panic!("unmatched bracket");
}

fn parse_perm_sets(s: &str) -> Vec<PermSetJson> {
    let mut sets = Vec::new();
    let bytes = s.as_bytes();
    let mut i = 1; // skip opening [

    while i < bytes.len() - 1 {
        // Find next { for a perm set object
        match s[i..].find('{') {
            Some(offset) => i += offset,
            None => break,
        }
        let obj_end = find_matching_bracket(s, i);
        let obj = &s[i..=obj_end];

        let count = extract_number(obj, "count");
        let textures = extract_string_array(obj, "textures");
        let perms = extract_perms(obj);

        sets.push(PermSetJson {
            count,
            textures,
            perms,
        });
        i = obj_end + 1;
    }
    sets
}

fn extract_number(obj: &str, key: &str) -> u32 {
    let pattern = format!("\"{key}\"");
    let pos = obj.find(&pattern).unwrap() + pattern.len();
    let after = &obj[pos..];
    let colon = after.find(':').unwrap();
    let num_start = colon + 1;
    let rest = after[num_start..].trim_start();
    let end = rest
        .find(|c: char| !c.is_ascii_digit())
        .unwrap_or(rest.len());
    rest[..end].parse().unwrap()
}

fn extract_string_array(obj: &str, key: &str) -> Vec<String> {
    let pattern = format!("\"{key}\"");
    let pos = obj.find(&pattern).unwrap() + pattern.len();
    let after = &obj[pos..];
    let arr_open = after.find('[').unwrap() + pos;
    // We need absolute position in obj
    let abs_open = arr_open;
    let abs_close = find_matching_bracket(obj, abs_open);
    let arr = &obj[abs_open + 1..abs_close];
    let mut result = Vec::new();
    let mut p = 0;
    while let Some(q_start) = arr[p..].find('"') {
        let abs_q = p + q_start + 1;
        let q_end = arr[abs_q..].find('"').unwrap() + abs_q;
        result.push(arr[abs_q..q_end].to_string());
        p = q_end + 1;
    }
    result
}

fn extract_perms(obj: &str) -> Vec<PermJson> {
    let pattern = "\"perms\"";
    let pos = obj.find(pattern).unwrap() + pattern.len();
    let after = &obj[pos..];
    let arr_open = after.find('[').unwrap() + pos;
    let arr_close = find_matching_bracket(obj, arr_open);
    let arr = &obj[arr_open + 1..arr_close];

    let mut perms = Vec::new();
    let mut p = 0;
    while let Some(obj_start) = arr[p..].find('{') {
        let abs_start = p + obj_start;
        let abs_end = find_matching_bracket(arr, abs_start);
        let perm_obj = &arr[abs_start..=abs_end];

        let bitmask = extract_string_value(perm_obj, "bitmask");
        let hash_str = extract_string_value(perm_obj, "hash");
        let hash = u32::from_str_radix(hash_str.trim_start_matches("0x"), 16).unwrap();

        perms.push(PermJson { bitmask, hash });
        p = abs_end + 1;
    }
    perms
}

fn extract_string_value(obj: &str, key: &str) -> String {
    let pattern = format!("\"{key}\"");
    let pos = obj.find(&pattern).unwrap() + pattern.len();
    let after = &obj[pos..];
    let colon = after.find(':').unwrap();
    let rest = &after[colon + 1..];
    let q_start = rest.find('"').unwrap() + 1;
    let q_end = rest[q_start..].find('"').unwrap() + q_start;
    rest[q_start..q_end].to_string()
}
