[package]
name = "pkg"
description = "Halo Wars 2 PKG format parsing"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[features]
default = []
std = ["nostdio/std"]

[dependencies]
nostdio.workspace = true
thiserror.workspace = true
