[package]
name = "xtd"
description = "XTD terrain displacement format parser for Halo Wars"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
ecf = { workspace = true }
nostdio.workspace = true
num-traits.workspace = true
thiserror = { workspace = true }
zerocopy.workspace = true

[dev-dependencies]
era = { workspace = true }
