[package]
name = "xmb-cli"
description = "CLI tool for XMB binary XML format conversion"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[lints]
workspace = true

[[bin]]
name = "xmb"
path = "src/main.rs"
doc = false

[dependencies]
xmb.workspace = true
ecf.workspace = true
clap.workspace = true
nostdio = { workspace = true, features = ["std"] }
