[package]
name = "bdt"
description = "BBinaryDataTree packed document format for Ensemble Studios games"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
hashbrown.workspace = true
nostdio.workspace = true
num-traits.workspace = true
thiserror.workspace = true
zerocopy.workspace = true
