[package]
name = "ecf"
description = "ECF (Ensemble Common Format) container handling"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
byteorder.workspace = true
flate2.workspace = true
thiserror.workspace = true
zerocopy.workspace = true
