[package]
name = "database-cli"
description = "CLI tool for validating HW1 game database files"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[[bin]]
name = "database-validate"
path = "src/main.rs"

[dependencies]
database.workspace = true
era.workspace = true
xmb.workspace = true
clap.workspace = true
bdt-serde.workspace = true
serde = { workspace = true, features = ["derive"] }
