//! Checked conversion between the HW1 v4 and HW2 v6 UGX representations.

use ugx::{Error, MaterialData, Result, UgxGeom, UgxVersion};

use crate::{GltfExportOptions, GltfImportOptions, export_to_gltf, import_from_gltf};

/// Convert a parsed UGX geometry into the selected game's representation.
///
/// Conversion uses the same metadata-preserving glTF intermediate as the
/// Blender workflow. Vertices are unpacked and repacked for the target game,
/// materials are converted between Legacy and Hogan representations, and all
/// derived geometry data is rebuilt by the importer.
///
/// # Errors
///
/// Returns an error if the source geometry cannot be exported, the target
/// representation cannot encode it, or structural data would be silently lost.
pub fn convert_ugx_version(source: &UgxGeom, target: UgxVersion) -> Result<UgxGeom> {
    let export = export_to_gltf(
        source,
        &GltfExportOptions {
            embed_buffers: false,
            include_materials: true,
            include_skeleton: true,
        },
    )?;
    let converted = import_from_gltf(
        &export.json,
        export.buffer.as_deref(),
        &GltfImportOptions {
            include_skeleton: true,
            include_materials: true,
            version: target,
        },
    )?;
    validate_conversion(source, &converted, target)?;
    Ok(converted)
}

/// Convert a parsed UGX geometry and serialize a strictly readable target file.
///
/// This is the high-level operation used by the CLI. It performs the semantic
/// conversion, invokes the target writer, and reads the generated bytes back
/// with strict validation before returning them.
///
/// # Errors
///
/// Returns an error under the same conditions as [`convert_ugx_version`], or
/// when the target writer or strict readback rejects the generated file.
pub fn convert_ugx_version_to_bytes(source: &UgxGeom, target: UgxVersion) -> Result<Vec<u8>> {
    let converted = convert_ugx_version(source, target)?;
    let bytes = ugx::Writer::write(&converted, target)?;
    let detected = ugx::detect_version(&bytes)?;
    if detected != target {
        return Err(Error::UnsupportedFormat(format!(
            "converted UGX identifies as {detected:?}, expected {target:?}"
        )));
    }
    ugx::Reader::read(&bytes)?;
    Ok(bytes)
}

fn validate_conversion(source: &UgxGeom, converted: &UgxGeom, target: UgxVersion) -> Result<()> {
    compare_count("sections", source.sections.len(), converted.sections.len())?;
    compare_count(
        "materials",
        source.materials.len(),
        converted.materials.len(),
    )?;
    compare_count("bones", source.bones.len(), converted.bones.len())?;
    compare_count(
        "Granny bones",
        source.granny_bones.len(),
        converted.granny_bones.len(),
    )?;
    compare_count(
        "Granny meshes",
        source.granny_meshes.len(),
        converted.granny_meshes.len(),
    )?;
    if source.max_instances != converted.max_instances {
        return conversion_error(&format!(
            "max instance count changed from {} to {}",
            source.max_instances, converted.max_instances
        ));
    }
    validate_sections(source, converted, target)?;
    validate_bones(source, converted)?;
    validate_materials(converted, target)
}

fn validate_sections(source: &UgxGeom, converted: &UgxGeom, target: UgxVersion) -> Result<()> {
    for (section_index, (source_section, converted_section)) in
        source.sections.iter().zip(&converted.sections).enumerate()
    {
        if source_section.num_verts != converted_section.num_verts
            || source_section.num_tris != converted_section.num_tris
            || source_section.material_index != converted_section.material_index
        {
            return conversion_error(&format!(
                "section {section_index} dimensions or material assignment changed"
            ));
        }
        let source_indices = source.get_section_indices(section_index)?;
        let converted_indices = converted.get_section_indices(section_index)?;
        if source_indices != converted_indices {
            return conversion_error(&format!("section {section_index} topology changed"));
        }
        let packers_match_target = match target {
            UgxVersion::Hw1 => {
                converted_section.base_vert_packer.is_some()
                    && converted_section.external_vert_packer.is_none()
            }
            UgxVersion::Hw2 => {
                converted_section.base_vert_packer.is_none()
                    && converted_section.external_vert_packer.is_some()
            }
        };
        if !packers_match_target {
            return conversion_error(&format!(
                "section {section_index} does not have the {target:?} vertex-packer representation"
            ));
        }
    }
    Ok(())
}

fn validate_bones(source: &UgxGeom, converted: &UgxGeom) -> Result<()> {
    for (bone_index, (source_bone, converted_bone)) in
        source.bones.iter().zip(&converted.bones).enumerate()
    {
        if source_bone.name != converted_bone.name
            || source_bone.parent_index != converted_bone.parent_index
        {
            return conversion_error(&format!("bone {bone_index} identity changed"));
        }
    }
    Ok(())
}

fn validate_materials(converted: &UgxGeom, target: UgxVersion) -> Result<()> {
    for (material_index, material) in converted.materials.iter().enumerate() {
        let is_target_material = match target {
            UgxVersion::Hw1 => {
                material.material_version == 4 && matches!(material.data, MaterialData::Legacy(_))
            }
            UgxVersion::Hw2 => matches!(material.data, MaterialData::Hogan(_)),
        };
        if !is_target_material {
            return conversion_error(&format!(
                "material {material_index} was not converted to the {target:?} representation"
            ));
        }
    }
    Ok(())
}

fn compare_count(label: &str, source: usize, converted: usize) -> Result<()> {
    if source == converted {
        Ok(())
    } else {
        conversion_error(&format!(
            "{label} count changed from {source} to {converted}"
        ))
    }
}

fn conversion_error<T>(message: &str) -> Result<T> {
    Err(Error::UnsupportedFormat(format!(
        "UGX version conversion would lose data: {message}"
    )))
}
