[package]
name = "ugx-gltf"
description = "glTF import/export for UGX (Unit Graphics) models"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
ugx = { workspace = true }
thiserror = { workspace = true }
half = { workspace = true }
gltf-json.workspace = true
gltf.workspace = true
serde_json.workspace = true
base64.workspace = true
serde = { workspace = true, features = ["derive"] }
num-traits.workspace = true

[dev-dependencies]
bdt = { workspace = true }
ecf = { workspace = true }
test-utils = { workspace = true }
