//! Bidirectional material conversion between Legacy (HW1) and Hogan (HW2).
//!
//! - [`legacy_to_hogan`]: Converts a Legacy map-based material to a Hogan shader-based material.
//! - [`hogan_to_legacy`]: Converts a Hogan shader-based material back to a Legacy map-based material.

use alloc::boxed::Box;
use alloc::string::String;
use alloc::vec;
use alloc::vec::Vec;

use super::{
    HoganFlag, HoganMaterialData, LegacyMaterialData, Map, MapType, Material, MaterialData,
    ShaderPermutation,
};

/// Default UFX version for Hogan materials.
const DEFAULT_UFX_VERSION: u32 = 9;

// ---------------------------------------------------------------------------
// Hogan texture slot names
// ---------------------------------------------------------------------------

/// Maps a Legacy [`MapType`] to the corresponding Hogan texture slot name.
///
/// Returns `None` for map types that have no direct Hogan equivalent.
fn hogan_texture_name(map_type: MapType) -> Option<&'static str> {
    match map_type {
        MapType::Diffuse => Some("Albedo_Map"),
        MapType::Normal => Some("Normal_Map"),
        // Gloss maps to BRDF + Specular (always paired), represented as BRDF here.
        MapType::Gloss => Some("BRDF_Parameter_Map"),
        MapType::Emissive => Some("Emissive_Map"),
        MapType::Opacity => Some("DissolveMask"),
        MapType::XForm => Some("Parallax_Map"),
        // No direct Hogan equivalent for these legacy map types.
        MapType::AO
        | MapType::Env
        | MapType::EnvMask
        | MapType::EmXForm
        | MapType::Distortion
        | MapType::Highlight
        | MapType::Modulate => None,
    }
}

/// `Specular_Reflectance` is always paired with `BRDF_Parameter_Map` in Hogan shaders.
/// This constant is used when Gloss is present to add both.
const SPECULAR_REFLECTANCE: &str = "Specular_Reflectance";

// ---------------------------------------------------------------------------
// Complete shader permutation catalog
// ---------------------------------------------------------------------------
// Sourced from a bulk dump of ~500 real HW2 `.ugx` assets.
//
// Each entry is `(name, hash)`. Entries are grouped into "permutation sets" —
// a material references 1–4 permutations (quality levels: Standard, High,
// Shadow, Shadow+). Single-entry sets use only slot `[0]`.
//
// The `count` in comments indicates how many materials in the dump used that
// exact permutation set.

/// A single shader permutation entry: `(name, hash)`.
pub type PermEntry = (&'static str, u32);

/// A permutation set: 1–4 quality-level entries used together by a material.
pub type PermSet = &'static [PermEntry];

// ---------------------------------------------------------------------------
// Generated permutation sets + texture metadata
// ---------------------------------------------------------------------------
// Source of truth: `src/data/hogan_perm_sets.json`
// Generated by `build.rs` — do not edit directly.
include!(concat!(env!("OUT_DIR"), "/hogan_perm_data.rs"));

/// Select the best-matching `HOGAN_STANDARD` permutation set for a given
/// set of required Hogan texture slot names.
///
/// Scoring: prefers perm sets that are an exact match or the smallest superset
/// of the needed textures. Multi-slot perm sets (4 quality levels) are preferred
/// over single-slot ones for better rendering quality.
fn select_standard_perm_set(needed: &[&str]) -> usize {
    let mut best_idx = 6; // fallback: base PBR, 4-slot (former DEFAULT_STATIC_PERMS)
    let mut best_score = i32::MIN;

    for (index, perm_textures) in HOGAN_STANDARD_PERM_TEXTURES.iter().enumerate() {
        // Count how many needed textures are present in this perm set
        let matched = needed.iter().filter(|n| perm_textures.contains(n)).count();
        // Count extra textures in this perm set that we don't need
        let extra = perm_textures.len().saturating_sub(matched);
        // Must have all needed textures
        if matched < needed.len() {
            continue;
        }
        // Prefer fewer extra textures (tighter match)
        let extra_penalty = i32::try_from(extra).unwrap_or(i32::MAX).saturating_mul(10);
        let mut score = 100i32.saturating_sub(extra_penalty);
        // Prefer multi-slot perm sets (4 quality levels)
        let num_slots = HOGAN_STANDARD_PERM_SETS[index].len();
        if num_slots >= 4 {
            score += 20;
        } else if num_slots >= 2 {
            score += 10;
        }
        // Prefer more frequently used perm sets (earlier index = more common)
        score = score.saturating_sub(i32::try_from(index).unwrap_or(i32::MAX));

        if score > best_score {
            best_score = score;
            best_idx = index;
        }
    }
    best_idx
}

/// Determine the required Hogan texture slot names for a Legacy material.
fn needed_hogan_textures(legacy: &LegacyMaterialData) -> Vec<&'static str> {
    let mut needed = Vec::new();
    for map_type in MapType::ALL {
        let has_map = legacy.maps[map_type as usize]
            .iter()
            .any(|m| !m.name.is_empty());
        if has_map && let Some(hogan_name) = hogan_texture_name(map_type) {
            if !needed.contains(&hogan_name) {
                needed.push(hogan_name);
            }
            // Gloss implies both BRDF_Parameter_Map and Specular_Reflectance
            if map_type == MapType::Gloss && !needed.contains(&SPECULAR_REFLECTANCE) {
                needed.push(SPECULAR_REFLECTANCE);
            }
        }
    }
    // If we have Albedo + Normal but no Gloss, still add BRDF + Specular
    // since all hogan_standard PBR permutations require them.
    let has_albedo = needed.contains(&"Albedo_Map");
    let has_normal = needed.contains(&"Normal_Map");
    let has_brdf = needed.contains(&"BRDF_Parameter_Map");
    if has_albedo && has_normal && !has_brdf {
        needed.push("BRDF_Parameter_Map");
        needed.push(SPECULAR_REFLECTANCE);
    }
    needed
}

// ---------------------------------------------------------------------------
// CB layout prediction from permutation bitflags
// ---------------------------------------------------------------------------
// Mirrors the logic in `ugx-gltf/src/hogan_cb_layout.rs::predict_cb8` so that
// the `ugx` crate (which is `no_std`) can build CB blobs without depending on
// `ugx-gltf`.

/// Extract the 64-bit feature flags from a Hogan permutation name.
///
/// Accepts names like `"HOGAN_STANDARD_00020000A83009A0"`.
fn parse_perm_flags(name: &str) -> Option<u64> {
    let hex_part = name.rsplit('_').next()?;
    u64::from_str_radix(hex_part, 16).ok()
}

/// CB layout entry: name and float offset.
struct CbEntry {
    name: &'static str,
    offset: u32,
}

/// Sequential layout builder (mirrors `hogan_cb_layout::LayoutBuilder`).
struct CbBuilder {
    entries: Vec<CbEntry>,
    pos: u32,
}

impl CbBuilder {
    fn new() -> Self {
        Self {
            entries: Vec::new(),
            pos: 0,
        }
    }

    fn push(&mut self, name: &'static str, components: u8) {
        self.entries.push(CbEntry {
            name,
            offset: self.pos,
        });
        self.pos += u32::from(components);
    }

    /// Advance to next register boundary (multiple of 4 floats).
    fn align_to_register(&mut self) {
        self.pos = (self.pos + 3) & !3;
    }

    /// Total float4 registers consumed.
    fn register_count(&self) -> u32 {
        self.pos.div_ceil(4)
    }
}

/// Predict the pixel-shader (CB8) layout from 64-bit flags.
///
/// This must match the layout produced by `hogan_cb_layout.rs::predict_cb8`
/// exactly, so that round-trip through glTF named parameters is lossless.
fn predict_ps_layout(flags: u64) -> CbBuilder {
    use HoganFlag::{
        Emissive, EmissiveSubA, EmissiveSubB, ExtraTextureLayer, MaterialOverride, PerChannelUv,
        ReducedTexturing, RoughnessChannel, ScrollAnim, SimplifiedTexturing,
    };

    let mut b = CbBuilder::new();

    // --- Group A: Core texturing (sequential packing) ---
    b.push("uv_scale_t0_t1", 2);
    b.push("uv_scale_t2_t3", 2);

    if !SimplifiedTexturing.test(flags) && !ReducedTexturing.test(flags) {
        b.push("normal_intensity", 1);
    }

    if ExtraTextureLayer.test(flags) || Emissive.test(flags) {
        b.push("uv_scale_t4", 1);
    }

    if Emissive.test(flags)
        || (ExtraTextureLayer.test(flags) && (EmissiveSubA.test(flags) || EmissiveSubB.test(flags)))
    {
        b.push("emissive_intensity", 1);
    }

    if PerChannelUv.test(flags) {
        b.push("uv_scale_t5", 1);
    }

    if ScrollAnim.test(flags) && Emissive.test(flags) {
        b.push("scroll_period", 1);
        b.push("scroll_phase", 1);
        b.push("fresnel_power", 1);
    }

    // --- Group B: Material overrides (starts at register boundary) ---
    let has_group_b = RoughnessChannel.test(flags) || MaterialOverride.test(flags);
    if has_group_b {
        b.align_to_register();

        if RoughnessChannel.test(flags) {
            b.push("roughness_channel_value", 1);
        }

        if MaterialOverride.test(flags) {
            b.push("detail_blend", 1);
            b.push("roughness_override", 1);
            b.push("override_strength", 1);
            b.align_to_register();
            b.push("spec_override_color", 3);
            b.push("override_bias", 1);
        }
    }

    b
}

/// Build the raw PS constant buffer bytes from predicted layout + Legacy props.
///
/// Maps Legacy material properties to Hogan CB parameters:
/// - `uv_scale_*`: `1.0` (native texture resolution)
/// - `normal_intensity`: `1.0` (full normal map effect)
/// - `emissive_intensity`: `1.0` when emissive map present, else `0.0`
/// - `roughness_channel_value` / `roughness_override`:
///   derived from `spec_power` as `1.0 - clamp(spec_power / 100, 0, 1)`
/// - `spec_override_color`: from Legacy `spec_color`
/// - `override_strength` / `override_bias` / `detail_blend`: `0.0` (disabled)
/// - `scroll_period`: `1.0`, `scroll_phase`: `0.0`, `fresnel_power`: `4.0`
fn build_ps_cb_data(flags: u64, legacy: &LegacyMaterialData) -> Vec<u8> {
    let layout = predict_ps_layout(flags);
    let regs = layout.register_count();
    if regs == 0 {
        return Vec::new();
    }

    let total_floats = usize::try_from(regs).unwrap_or_default() * 4;
    let mut floats = vec![0.0f32; total_floats];

    let has_emissive = legacy.maps[MapType::Emissive as usize]
        .iter()
        .any(|m| !m.name.is_empty());
    let roughness = 1.0 - (legacy.spec_power / 100.0).clamp(0.0, 1.0);

    for entry in &layout.entries {
        let off = usize::try_from(entry.offset).unwrap_or_default();
        match entry.name {
            "uv_scale_t0_t1" | "uv_scale_t2_t3" => {
                floats[off] = 1.0;
                floats[off + 1] = 1.0;
            }
            "normal_intensity" | "uv_scale_t4" | "uv_scale_t5" | "scroll_period" => {
                floats[off] = 1.0;
            }
            "emissive_intensity" => floats[off] = if has_emissive { 1.0 } else { 0.0 },
            "scroll_phase" | "detail_blend" | "override_strength" | "override_bias" => {
                floats[off] = 0.0;
            }
            "fresnel_power" => floats[off] = legacy.env_fresnel_power,
            "roughness_channel_value" | "roughness_override" => floats[off] = roughness,
            "spec_override_color" => {
                floats[off] = legacy.spec_color[0];
                floats[off + 1] = legacy.spec_color[1];
                floats[off + 2] = legacy.spec_color[2];
            }
            _ => {}
        }
    }

    // Serialize as LE f32 bytes.
    let mut out = Vec::with_capacity(total_floats * 4);
    for &f in &floats {
        out.extend_from_slice(&f.to_le_bytes());
    }
    out
}

/// Convert a Legacy (HW1) material to Hogan (HW2) format.
///
/// Mapping rules:
/// - Diffuse map path stem → `textures` string using the HW2 `[al]` suffix pattern.
/// - `blend_type` → `blend_mode` (direct mapping).
/// - Automatically selects the best-matching `HOGAN_STANDARD` shader permutation
///   set based on which Legacy map types are populated.
/// - `skinned`: set to `true` when any mesh section using this material has
///   bone-weight skinning (i.e. `!rigid_only && max_bones > 0`).
///
/// # Constant Buffer Data
///
/// The pixel shader CB data (`ps_cb_data`) is populated with sensible defaults
/// derived from the Legacy material properties and the selected permutation's
/// bitflags.  The layout is predicted from the first permutation's 64-bit flags
/// using the same algorithm as `hogan_cb_layout.rs`, ensuring that the glTF
/// exporter can decode the blob back into named parameters.
///
/// Vertex/hull/domain/geometry CB blobs remain empty (the common permutations
/// selected by this converter don't require VS CB parameters).
#[must_use]
pub fn legacy_to_hogan(legacy: &LegacyMaterialData, skinned: bool) -> HoganMaterialData {
    let textures = build_hogan_textures(legacy);
    let needed = needed_hogan_textures(legacy);
    let perm_idx = select_standard_perm_set(&needed);
    let perm_set = HOGAN_STANDARD_PERM_SETS[perm_idx];

    let shader_permutations: Vec<ShaderPermutation> = perm_set
        .iter()
        .map(|(name, hash)| ShaderPermutation {
            name: String::from(*name),
            hash: *hash,
        })
        .collect();

    // Build PS CB data from the first permutation's flags + legacy properties.
    let ps_cb_data = shader_permutations
        .first()
        .and_then(|p| parse_perm_flags(&p.name))
        .map(|flags| build_ps_cb_data(flags, legacy))
        .unwrap_or_default();

    HoganMaterialData {
        shader_permutations,
        ufx_version: DEFAULT_UFX_VERSION,
        blend_mode: u32::from(legacy.blend_type),
        shadow_requires_consts: false,
        skinned,
        terrain_blending: false,
        vs_cb_data: Vec::new(),
        ps_cb_data,
        hs_cb_data: Vec::new(),
        ds_cb_data: Vec::new(),
        gs_cb_data: Vec::new(),
        textures,
    }
}

/// Convert a Hogan (HW2) material to Legacy (HW1) format.
///
/// Mapping rules:
/// - `textures` string → parsed into diffuse/normal/gloss/emissive/opacity paths by suffix.
/// - `blend_mode` → `blend_type`.
/// - Specular and other Legacy properties use defaults since Hogan
///   doesn't carry equivalent data.
#[must_use]
pub fn hogan_to_legacy(hogan: &HoganMaterialData) -> LegacyMaterialData {
    let mut legacy = LegacyMaterialData {
        blend_type: u8::try_from(hogan.blend_mode).unwrap_or_default(),
        ..LegacyMaterialData::default()
    };

    let parsed = parse_textures_string(&hogan.textures);
    let flag = 7u16;
    if let Some(path) = parsed.diffuse {
        legacy.maps[MapType::Diffuse as usize] = vec![Map {
            name: path,
            channel: 0,
            flags: flag,
        }];
    }

    if let Some(path) = parsed.normal {
        legacy.maps[MapType::Normal as usize] = vec![Map {
            name: path,
            channel: 0,
            flags: flag,
        }];
    }

    if let Some(path) = parsed.gloss {
        legacy.maps[MapType::Gloss as usize] = vec![Map {
            name: path,
            channel: 0,
            flags: flag,
        }];
    }

    if let Some(path) = parsed.emissive {
        legacy.maps[MapType::Emissive as usize] = vec![Map {
            name: path,
            channel: 0,
            flags: flag,
        }];
    }

    if let Some(path) = parsed.opacity {
        legacy.maps[MapType::Opacity as usize] = vec![Map {
            name: path,
            channel: 0,
            flags: flag,
        }];
    }

    legacy
}

/// Convert a full [`Material`], switching between Legacy ↔ Hogan as needed.
///
/// - If the material is already in the target format, it is cloned unchanged.
/// - `to_hogan = true`: Legacy → Hogan; `to_hogan = false`: Hogan → Legacy.
/// - `skinned`: whether this material is used on a skinned mesh section.
#[must_use]
pub fn convert_material(mat: &Material, to_hogan: bool, skinned: bool) -> Material {
    let data = match (&mat.data, to_hogan) {
        (MaterialData::Legacy(l), true) => {
            MaterialData::Hogan(Box::new(legacy_to_hogan(l, skinned)))
        }
        (MaterialData::Hogan(h), false) => MaterialData::Legacy(Box::new(hogan_to_legacy(h))),
        (MaterialData::Legacy(_), false) | (MaterialData::Hogan(_), true) => mat.data.clone(),
    };

    Material {
        name: mat.name.clone(),
        material_version: 4,
        data,
    }
}

/// Determine whether each material in a [`crate::UgxGeom`] is skinned.
///
/// A material is considered skinned if *any* section referencing it
/// has bone-weight skinning (`!rigid_only && max_bones > 0`).
///
/// Returns a `Vec<bool>` with one entry per material index.
#[must_use]
pub fn material_skinned_flags(geom: &super::UgxGeom) -> Vec<bool> {
    let n = geom.materials.len();
    let mut flags = alloc::vec![false; n];
    for section in &geom.sections {
        if let Ok(index) = usize::try_from(section.material_index)
            && index < n
            && !section.rigid_only
            && section.max_bones > 0
        {
            flags[index] = true;
        }
    }
    flags
}

/// Convert all materials in a [`crate::UgxGeom`], automatically determining
/// the `skinned` flag for each material from section data.
///
/// - `to_hogan = true`: Legacy → Hogan; `to_hogan = false`: Hogan → Legacy.
///
/// Returns a new `Vec<Material>` with converted materials.
#[must_use]
pub fn convert_geom_materials(geom: &super::UgxGeom, to_hogan: bool) -> Vec<Material> {
    let skinned_flags = material_skinned_flags(geom);
    geom.materials
        .iter()
        .enumerate()
        .map(|(i, mat)| {
            let skinned = skinned_flags.get(i).copied().unwrap_or(false);
            convert_material(mat, to_hogan, skinned)
        })
        .collect()
}

// ---------------------------------------------------------------------------
// Texture string helpers
// ---------------------------------------------------------------------------

struct ParsedTextures {
    diffuse: Option<String>,
    normal: Option<String>,
    gloss: Option<String>,
    emissive: Option<String>,
    opacity: Option<String>,
}

/// Build a Hogan `textures` string from Legacy map paths.
///
/// HW2 uses a pattern like `bespoke\path\to\model_[al]` where `[al]` indicates
/// the texture set base name. We derive this from the diffuse map path by stripping
/// the `_diff` suffix and file extension, then appending `_[al]`.
///
/// If no diffuse map exists, falls back to joining all non-empty paths with semicolons.
fn build_hogan_textures(legacy: &LegacyMaterialData) -> String {
    // Try to derive from the diffuse map path (most common case).
    if let Some(diffuse_map) = legacy.maps[MapType::Diffuse as usize]
        .first()
        .filter(|m| !m.name.is_empty())
    {
        let path = &diffuse_map.name;
        // Strip file extension
        let stem = path
            .rfind('.')
            .map_or(path.as_str(), |index| &path[..index]);
        // Strip common diffuse suffixes to get the base name
        let base = strip_suffix_ci(stem, "_diff")
            .or_else(|| strip_suffix_ci(stem, "_al"))
            .or_else(|| strip_suffix_ci(stem, "_albedo"))
            .or_else(|| strip_suffix_ci(stem, "_d"))
            .unwrap_or(stem);
        let mut result = String::from(base);
        result.push_str("_[al]");
        return result;
    }
    // Fallback: join all non-empty map paths with semicolons.
    let mut parts: Vec<&str> = Vec::new();
    for map_type in MapType::ALL {
        for map in &legacy.maps[map_type as usize] {
            if !map.name.is_empty() {
                parts.push(&map.name);
            }
        }
    }
    let mut result = String::new();
    for (i, part) in parts.iter().enumerate() {
        if i > 0 {
            result.push(';');
        }
        result.push_str(part);
    }
    result
}

/// Case-insensitive suffix strip. Returns the string without the suffix if it matches.
fn strip_suffix_ci<'a>(s: &'a str, suffix: &str) -> Option<&'a str> {
    let slen = s.len();
    let xlen = suffix.len();
    if slen >= xlen && s[slen - xlen..].eq_ignore_ascii_case(suffix) {
        Some(&s[..slen - xlen])
    } else {
        None
    }
}

/// Parse a Hogan `textures` string into individual Legacy map paths.
///
/// Handles two formats:
/// 1. **Bracket pattern** (real HW2): `path\to\model_[al]`
///    → generates `path\to\model_diff.ddx` for diffuse, `path\to\model_norm.ddx` for normal
/// 2. **Semicolon-separated** (fallback): `path_diff.ddx;path_norm.ddx`
///    → classifies each path by its filename suffix
fn parse_textures_string(textures: &str) -> ParsedTextures {
    let mut parsed = ParsedTextures {
        diffuse: None,
        normal: None,
        gloss: None,
        emissive: None,
        opacity: None,
    };
    if textures.is_empty() {
        return parsed;
    }

    // Check for HW2 bracket pattern: `base_[al]`
    if let Some(bracket_pos) = textures.find("[al]") {
        let base = &textures[..bracket_pos];
        parsed.diffuse = Some(alloc::format!("{base}diff.ddx"));
        parsed.normal = Some(alloc::format!("{base}norm.ddx"));
        return parsed;
    }
    // Check for `[nm]` pattern (normal-only, e.g. water shaders)
    if let Some(bracket_pos) = textures.find("[nm]") {
        let base = &textures[..bracket_pos];
        parsed.normal = Some(alloc::format!("{base}nm.ddx"));
        return parsed;
    }

    // Fallback: semicolon-separated paths classified by suffix.
    for part in textures.split(';') {
        let trimmed = part.trim();
        if trimmed.is_empty() {
            continue;
        }
        let lower = trimmed.to_lowercase();
        let stem = lower
            .rfind('.')
            .map_or(lower.as_str(), |index| &lower[..index]);

        if stem.ends_with("_diff")
            || stem.ends_with("_al")
            || stem.ends_with("_albedo")
            || stem.ends_with("_d")
        {
            if parsed.diffuse.is_none() {
                parsed.diffuse = Some(String::from(trimmed));
            }
        } else if stem.ends_with("_norm") || stem.ends_with("_nm") || stem.ends_with("_n") {
            if parsed.normal.is_none() {
                parsed.normal = Some(String::from(trimmed));
            }
        } else if stem.ends_with("_spec")
            || stem.ends_with("_gloss")
            || stem.ends_with("_s")
            || stem.ends_with("_g")
        {
            if parsed.gloss.is_none() {
                parsed.gloss = Some(String::from(trimmed));
            }
        } else if stem.ends_with("_em") || stem.ends_with("_emissive") {
            if parsed.emissive.is_none() {
                parsed.emissive = Some(String::from(trimmed));
            }
        } else if stem.ends_with("_op") || stem.ends_with("_opacity") || stem.ends_with("_alpha") {
            if parsed.opacity.is_none() {
                parsed.opacity = Some(String::from(trimmed));
            }
        } else if parsed.diffuse.is_none() {
            parsed.diffuse = Some(String::from(trimmed));
        }
    }
    parsed
}

#[cfg(test)]
#[path = "convert_tests.rs"]
mod tests;
