//! Bidirectional material conversion between Legacy (HW1) and Hogan (HW2).
//!
//! - [`legacy_to_hogan`]: Converts a Legacy map-based material to a Hogan shader-based material.
//! - [`hogan_to_legacy`]: Converts a Hogan shader-based material back to a Legacy map-based material.

use alloc::boxed::Box;
use alloc::string::String;
use alloc::vec;
use alloc::vec::Vec;

use super::{
    HoganMaterialData, LegacyMaterialData, Map, MapType, Material, MaterialData, ShaderPermutation,
};

/// Default UFX version for Hogan materials.
const DEFAULT_UFX_VERSION: u32 = 9;

// ---------------------------------------------------------------------------
// Hogan texture slot names
// ---------------------------------------------------------------------------

/// Maps a Legacy [`MapType`] to the corresponding Hogan texture slot name.
///
/// Returns `None` for map types that have no direct Hogan equivalent.
fn hogan_texture_name(map_type: MapType) -> Option<&'static str> {
    match map_type {
        MapType::Diffuse => Some("Albedo_Map"),
        MapType::Normal => Some("Normal_Map"),
        // Gloss maps to BRDF + Specular (always paired), represented as BRDF here.
        MapType::Gloss => Some("BRDF_Parameter_Map"),
        MapType::Emissive => Some("Emissive_Map"),
        MapType::Opacity => Some("DissolveMask"),
        MapType::XForm => Some("Parallax_Map"),
        // No direct Hogan equivalent for these legacy map types.
        MapType::AO
        | MapType::Env
        | MapType::EnvMask
        | MapType::EmXForm
        | MapType::Distortion
        | MapType::Highlight
        | MapType::Modulate => None,
    }
}

/// Specular_Reflectance is always paired with BRDF_Parameter_Map in Hogan shaders.
/// This constant is used when Gloss is present to add both.
const SPECULAR_REFLECTANCE: &str = "Specular_Reflectance";

// ---------------------------------------------------------------------------
// Complete shader permutation catalog
// ---------------------------------------------------------------------------
// Sourced from a bulk dump of ~500 real HW2 `.ugx` assets.
//
// Each entry is `(name, hash)`. Entries are grouped into "permutation sets" —
// a material references 1–4 permutations (quality levels: Standard, High,
// Shadow, Shadow+). Single-entry sets use only slot `[0]`.
//
// The `count` in comments indicates how many materials in the dump used that
// exact permutation set.

/// A single shader permutation entry: `(name, hash)`.
#[allow(dead_code)]
pub type PermEntry = (&'static str, u32);

/// A permutation set: 1–4 quality-level entries used together by a material.
#[allow(dead_code)]
pub type PermSet = &'static [PermEntry];

// ---------------------------------------------------------------------------
// Generated permutation sets + texture metadata
// ---------------------------------------------------------------------------
// Source of truth: `src/data/hogan_perm_sets.json`
// Generated by `build.rs` — do not edit directly.
include!(concat!(env!("OUT_DIR"), "/hogan_perm_data.rs"));

/// Select the best-matching `HOGAN_STANDARD` permutation set for a given
/// set of required Hogan texture slot names.
///
/// Scoring: prefers perm sets that are an exact match or the smallest superset
/// of the needed textures. Multi-slot perm sets (4 quality levels) are preferred
/// over single-slot ones for better rendering quality.
fn select_standard_perm_set(needed: &[&str]) -> usize {
    let mut best_idx = 6; // fallback: base PBR, 4-slot (former DEFAULT_STATIC_PERMS)
    let mut best_score = i32::MIN;

    for (i, perm_textures) in HOGAN_STANDARD_PERM_TEXTURES.iter().enumerate() {
        // Count how many needed textures are present in this perm set
        let matched = needed.iter().filter(|n| perm_textures.contains(n)).count();
        // Count extra textures in this perm set that we don't need
        let extra = perm_textures.len().saturating_sub(matched);
        // Must have all needed textures
        if matched < needed.len() {
            continue;
        }
        // Prefer fewer extra textures (tighter match)
        let mut score: i32 = 100 - (extra as i32 * 10);
        // Prefer multi-slot perm sets (4 quality levels)
        let num_slots = HOGAN_STANDARD_PERM_SETS[i].len();
        if num_slots >= 4 {
            score += 20;
        } else if num_slots >= 2 {
            score += 10;
        }
        // Prefer more frequently used perm sets (earlier index = more common)
        score -= i as i32;

        if score > best_score {
            best_score = score;
            best_idx = i;
        }
    }
    best_idx
}

/// Determine the required Hogan texture slot names for a Legacy material.
fn needed_hogan_textures(legacy: &LegacyMaterialData) -> Vec<&'static str> {
    let mut needed = Vec::new();
    for map_type in MapType::ALL {
        let has_map = legacy.maps[map_type as usize]
            .iter()
            .any(|m| !m.name.is_empty());
        if has_map && let Some(hogan_name) = hogan_texture_name(map_type) {
            if !needed.contains(&hogan_name) {
                needed.push(hogan_name);
            }
            // Gloss implies both BRDF_Parameter_Map and Specular_Reflectance
            if map_type == MapType::Gloss && !needed.contains(&SPECULAR_REFLECTANCE) {
                needed.push(SPECULAR_REFLECTANCE);
            }
        }
    }
    // If we have Albedo + Normal but no Gloss, still add BRDF + Specular
    // since all hogan_standard PBR permutations require them.
    let has_albedo = needed.contains(&"Albedo_Map");
    let has_normal = needed.contains(&"Normal_Map");
    let has_brdf = needed.contains(&"BRDF_Parameter_Map");
    if has_albedo && has_normal && !has_brdf {
        needed.push("BRDF_Parameter_Map");
        needed.push(SPECULAR_REFLECTANCE);
    }
    needed
}

/// Convert a Legacy (HW1) material to Hogan (HW2) format.
///
/// Mapping rules:
/// - Diffuse map path stem → `textures` string using the HW2 `[al]` suffix pattern.
/// - `blend_type` → `blend_mode` (direct mapping).
/// - Automatically selects the best-matching `HOGAN_STANDARD` shader permutation
///   set based on which Legacy map types are populated.
/// - `skinned`: set to `true` when any mesh section using this material has
///   bone-weight skinning (i.e. `!rigid_only && max_bones > 0`).
///
/// # Constant Buffer Data
///
/// All five CB data blobs (`vs_cb_data` … `gs_cb_data`) default to empty.
/// In real HW2 assets these contain raw binary that the engine `memcpy`s
/// into the GPU constant buffer before rendering.  Empty blobs cause the
/// shader to use its compiled-in defaults, which is correct for converted
/// materials.
pub fn legacy_to_hogan(legacy: &LegacyMaterialData, skinned: bool) -> HoganMaterialData {
    let textures = build_hogan_textures(legacy);
    let needed = needed_hogan_textures(legacy);
    let perm_idx = select_standard_perm_set(&needed);
    let perm_set = HOGAN_STANDARD_PERM_SETS[perm_idx];

    let shader_permutations = perm_set
        .iter()
        .map(|(name, hash)| ShaderPermutation {
            name: String::from(*name),
            hash: *hash,
        })
        .collect();

    HoganMaterialData {
        shader_permutations,
        ufx_version: DEFAULT_UFX_VERSION,
        blend_mode: legacy.blend_type as u32,
        shadow_requires_consts: false,
        skinned,
        terrain_blending: false,
        vs_cb_data: Vec::new(),
        ps_cb_data: Vec::new(),
        hs_cb_data: Vec::new(),
        ds_cb_data: Vec::new(),
        gs_cb_data: Vec::new(),
        textures,
    }
}

/// Convert a Hogan (HW2) material to Legacy (HW1) format.
///
/// Mapping rules:
/// - `textures` string → parsed into diffuse/normal/gloss/emissive/opacity paths by suffix.
/// - `blend_mode` → `blend_type`.
/// - Specular and other Legacy properties use defaults since Hogan
///   doesn't carry equivalent data.
pub fn hogan_to_legacy(hogan: &HoganMaterialData) -> LegacyMaterialData {
    let mut legacy = LegacyMaterialData {
        blend_type: hogan.blend_mode as u8,
        ..LegacyMaterialData::default()
    };

    let parsed = parse_textures_string(&hogan.textures);
    let flag = 7u8;
    if let Some(path) = parsed.diffuse {
        legacy.maps[MapType::Diffuse as usize] = vec![Map {
            name: path,
            channel: 0,
            flags: flag,
        }];
    }

    if let Some(path) = parsed.normal {
        legacy.maps[MapType::Normal as usize] = vec![Map {
            name: path,
            channel: 0,
            flags: flag,
        }];
    }

    if let Some(path) = parsed.gloss {
        legacy.maps[MapType::Gloss as usize] = vec![Map {
            name: path,
            channel: 0,
            flags: flag,
        }];
    }

    if let Some(path) = parsed.emissive {
        legacy.maps[MapType::Emissive as usize] = vec![Map {
            name: path,
            channel: 0,
            flags: flag,
        }];
    }

    if let Some(path) = parsed.opacity {
        legacy.maps[MapType::Opacity as usize] = vec![Map {
            name: path,
            channel: 0,
            flags: flag,
        }];
    }

    legacy
}

/// Convert a full [`Material`], switching between Legacy ↔ Hogan as needed.
///
/// - If the material is already in the target format, it is cloned unchanged.
/// - `to_hogan = true`: Legacy → Hogan; `to_hogan = false`: Hogan → Legacy.
/// - `skinned`: whether this material is used on a skinned mesh section.
pub fn convert_material(mat: &Material, to_hogan: bool, skinned: bool) -> Material {
    let data = match (&mat.data, to_hogan) {
        (MaterialData::Legacy(l), true) => {
            MaterialData::Hogan(Box::new(legacy_to_hogan(l, skinned)))
        }
        (MaterialData::Hogan(h), false) => MaterialData::Legacy(Box::new(hogan_to_legacy(h))),
        (MaterialData::Legacy(_), false) | (MaterialData::Hogan(_), true) => mat.data.clone(),
    };

    Material {
        name: mat.name.clone(),
        material_version: 4,
        data,
    }
}

/// Determine whether each material in a [`UgxGeom`] is skinned.
///
/// A material is considered skinned if *any* section referencing it
/// has bone-weight skinning (`!rigid_only && max_bones > 0`).
///
/// Returns a `Vec<bool>` with one entry per material index.
pub fn material_skinned_flags(geom: &super::UgxGeom) -> Vec<bool> {
    let n = geom.materials.len();
    let mut flags = alloc::vec![false; n];
    for section in &geom.sections {
        let idx = section.material_index as usize;
        if idx < n && !section.rigid_only && section.max_bones > 0 {
            flags[idx] = true;
        }
    }
    flags
}

/// Convert all materials in a [`UgxGeom`], automatically determining
/// the `skinned` flag for each material from section data.
///
/// - `to_hogan = true`: Legacy → Hogan; `to_hogan = false`: Hogan → Legacy.
///
/// Returns a new `Vec<Material>` with converted materials.
pub fn convert_geom_materials(geom: &super::UgxGeom, to_hogan: bool) -> Vec<Material> {
    let skinned_flags = material_skinned_flags(geom);
    geom.materials
        .iter()
        .enumerate()
        .map(|(i, mat)| {
            let skinned = skinned_flags.get(i).copied().unwrap_or(false);
            convert_material(mat, to_hogan, skinned)
        })
        .collect()
}

// ---------------------------------------------------------------------------
// Texture string helpers
// ---------------------------------------------------------------------------

struct ParsedTextures {
    diffuse: Option<String>,
    normal: Option<String>,
    gloss: Option<String>,
    emissive: Option<String>,
    opacity: Option<String>,
}

/// Build a Hogan `textures` string from Legacy map paths.
///
/// HW2 uses a pattern like `bespoke\path\to\model_[al]` where `[al]` indicates
/// the texture set base name. We derive this from the diffuse map path by stripping
/// the `_diff` suffix and file extension, then appending `_[al]`.
///
/// If no diffuse map exists, falls back to joining all non-empty paths with semicolons.
fn build_hogan_textures(legacy: &LegacyMaterialData) -> String {
    // Try to derive from the diffuse map path (most common case).
    if let Some(diffuse_map) = legacy.maps[MapType::Diffuse as usize]
        .first()
        .filter(|m| !m.name.is_empty())
    {
        let path = &diffuse_map.name;
        // Strip file extension
        let stem = path.rfind('.').map(|i| &path[..i]).unwrap_or(path);
        // Strip common diffuse suffixes to get the base name
        let base = strip_suffix_ci(stem, "_diff")
            .or_else(|| strip_suffix_ci(stem, "_al"))
            .or_else(|| strip_suffix_ci(stem, "_albedo"))
            .or_else(|| strip_suffix_ci(stem, "_d"))
            .unwrap_or(stem);
        let mut result = String::from(base);
        result.push_str("_[al]");
        return result;
    }
    // Fallback: join all non-empty map paths with semicolons.
    let mut parts: Vec<&str> = Vec::new();
    for map_type in MapType::ALL {
        for map in &legacy.maps[map_type as usize] {
            if !map.name.is_empty() {
                parts.push(&map.name);
            }
        }
    }
    let mut result = String::new();
    for (i, part) in parts.iter().enumerate() {
        if i > 0 {
            result.push(';');
        }
        result.push_str(part);
    }
    result
}

/// Case-insensitive suffix strip. Returns the string without the suffix if it matches.
fn strip_suffix_ci<'a>(s: &'a str, suffix: &str) -> Option<&'a str> {
    let slen = s.len();
    let xlen = suffix.len();
    if slen >= xlen && s[slen - xlen..].eq_ignore_ascii_case(suffix) {
        Some(&s[..slen - xlen])
    } else {
        None
    }
}

/// Parse a Hogan `textures` string into individual Legacy map paths.
///
/// Handles two formats:
/// 1. **Bracket pattern** (real HW2): `path\to\model_[al]`
///    → generates `path\to\model_diff.ddx` for diffuse, `path\to\model_norm.ddx` for normal
/// 2. **Semicolon-separated** (fallback): `path_diff.ddx;path_norm.ddx`
///    → classifies each path by its filename suffix
fn parse_textures_string(textures: &str) -> ParsedTextures {
    let mut parsed = ParsedTextures {
        diffuse: None,
        normal: None,
        gloss: None,
        emissive: None,
        opacity: None,
    };
    if textures.is_empty() {
        return parsed;
    }

    // Check for HW2 bracket pattern: `base_[al]`
    if let Some(bracket_pos) = textures.find("[al]") {
        let base = &textures[..bracket_pos];
        parsed.diffuse = Some(alloc::format!("{}diff.ddx", base));
        parsed.normal = Some(alloc::format!("{}norm.ddx", base));
        return parsed;
    }
    // Check for `[nm]` pattern (normal-only, e.g. water shaders)
    if let Some(bracket_pos) = textures.find("[nm]") {
        let base = &textures[..bracket_pos];
        parsed.normal = Some(alloc::format!("{}nm.ddx", base));
        return parsed;
    }

    // Fallback: semicolon-separated paths classified by suffix.
    for part in textures.split(';') {
        let trimmed = part.trim();
        if trimmed.is_empty() {
            continue;
        }
        let lower = trimmed.to_lowercase();
        let stem = lower.rfind('.').map(|i| &lower[..i]).unwrap_or(&lower);

        if stem.ends_with("_diff")
            || stem.ends_with("_al")
            || stem.ends_with("_albedo")
            || stem.ends_with("_d")
        {
            if parsed.diffuse.is_none() {
                parsed.diffuse = Some(String::from(trimmed));
            }
        } else if stem.ends_with("_norm") || stem.ends_with("_nm") || stem.ends_with("_n") {
            if parsed.normal.is_none() {
                parsed.normal = Some(String::from(trimmed));
            }
        } else if stem.ends_with("_spec")
            || stem.ends_with("_gloss")
            || stem.ends_with("_s")
            || stem.ends_with("_g")
        {
            if parsed.gloss.is_none() {
                parsed.gloss = Some(String::from(trimmed));
            }
        } else if stem.ends_with("_em") || stem.ends_with("_emissive") {
            if parsed.emissive.is_none() {
                parsed.emissive = Some(String::from(trimmed));
            }
        } else if stem.ends_with("_op") || stem.ends_with("_opacity") || stem.ends_with("_alpha") {
            if parsed.opacity.is_none() {
                parsed.opacity = Some(String::from(trimmed));
            }
        } else if parsed.diffuse.is_none() {
            parsed.diffuse = Some(String::from(trimmed));
        }
    }
    parsed
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_legacy_to_hogan_produces_al_pattern() {
        let mut legacy = LegacyMaterialData::default();
        legacy.maps[MapType::Diffuse as usize] = vec![Map {
            name: String::from("art\\textures\\grass_diff.ddx"),
            channel: 0,
            flags: 7,
        }];
        legacy.blend_type = 1;

        let hogan = legacy_to_hogan(&legacy, false);
        assert_eq!(hogan.ufx_version, DEFAULT_UFX_VERSION);
        assert_eq!(hogan.blend_mode, 1);
        assert!(!hogan.skinned);
        assert_eq!(hogan.shader_permutations.len(), 4);
        // Should produce HW2-style [al] texture pattern
        assert_eq!(hogan.textures, "art\\textures\\grass_[al]");
    }

    #[test]
    fn test_hogan_to_legacy_bracket_pattern() {
        let hogan = HoganMaterialData {
            shader_permutations: vec![ShaderPermutation {
                name: String::from("HOGAN_STANDARD_00000000003009A0"),
                hash: 0xE0EE_7237,
            }],
            ufx_version: 9,
            blend_mode: 2,
            shadow_requires_consts: false,
            skinned: false,
            terrain_blending: false,
            vs_cb_data: Vec::new(),
            ps_cb_data: Vec::new(),
            hs_cb_data: Vec::new(),
            ds_cb_data: Vec::new(),
            gs_cb_data: Vec::new(),
            textures: String::from("bespoke\\units\\scorpion\\scorpion_[al]"),
        };
        let legacy = hogan_to_legacy(&hogan);
        assert_eq!(legacy.blend_type, 2);
        assert_eq!(
            legacy.maps[MapType::Diffuse as usize][0].name,
            "bespoke\\units\\scorpion\\scorpion_diff.ddx"
        );
        assert_eq!(
            legacy.maps[MapType::Normal as usize][0].name,
            "bespoke\\units\\scorpion\\scorpion_norm.ddx"
        );
    }

    #[test]
    fn test_hogan_to_legacy_semicolon_fallback() {
        let hogan = HoganMaterialData {
            shader_permutations: vec![],
            ufx_version: 9,
            blend_mode: 0,
            shadow_requires_consts: false,
            skinned: false,
            terrain_blending: false,
            vs_cb_data: Vec::new(),
            ps_cb_data: Vec::new(),
            hs_cb_data: Vec::new(),
            ds_cb_data: Vec::new(),
            gs_cb_data: Vec::new(),
            textures: String::from("art\\grass_diff.ddx;art\\grass_norm.ddx"),
        };
        let legacy = hogan_to_legacy(&hogan);
        assert_eq!(legacy.maps[MapType::Diffuse as usize].len(), 1);
        assert_eq!(legacy.maps[MapType::Normal as usize].len(), 1);
    }

    #[test]
    fn test_hogan_to_legacy_empty() {
        let hogan = HoganMaterialData {
            shader_permutations: vec![],
            ufx_version: 9,
            blend_mode: 0,
            shadow_requires_consts: false,
            skinned: false,
            terrain_blending: false,
            vs_cb_data: Vec::new(),
            ps_cb_data: Vec::new(),
            hs_cb_data: Vec::new(),
            ds_cb_data: Vec::new(),
            gs_cb_data: Vec::new(),
            textures: String::new(),
        };
        let legacy = hogan_to_legacy(&hogan);
        for maps in &legacy.maps {
            assert!(maps.is_empty());
        }
    }

    #[test]
    fn test_hogan_to_legacy_nm_pattern() {
        let hogan = HoganMaterialData {
            shader_permutations: vec![],
            ufx_version: 9,
            blend_mode: 8,
            shadow_requires_consts: false,
            skinned: false,
            terrain_blending: false,
            vs_cb_data: Vec::new(),
            ps_cb_data: Vec::new(),
            hs_cb_data: Vec::new(),
            ds_cb_data: Vec::new(),
            gs_cb_data: Vec::new(),
            textures: String::from("environment_tiling\\water\\fx_water_01[nm]"),
        };
        let legacy = hogan_to_legacy(&hogan);
        assert!(legacy.maps[MapType::Diffuse as usize].is_empty());
        assert_eq!(
            legacy.maps[MapType::Normal as usize][0].name,
            "environment_tiling\\water\\fx_water_01nm.ddx"
        );
    }

    #[test]
    fn test_convert_material_roundtrip() {
        let mut ld = LegacyMaterialData::default();
        ld.maps[MapType::Diffuse as usize] = vec![Map {
            name: String::from("art\\model_diff.ddx"),
            channel: 0,
            flags: 7,
        }];
        let mat = Material {
            name: String::from("test"),
            material_version: 4,
            data: MaterialData::Legacy(Box::new(ld)),
        };
        let to_h = convert_material(&mat, true, false);
        assert!(to_h.is_hogan());
        assert_eq!(to_h.hogan().unwrap().textures, "art\\model_[al]");
        let back = convert_material(&to_h, false, false);
        assert!(back.is_legacy());
        assert!(
            back.legacy().unwrap().maps[MapType::Diffuse as usize][0]
                .name
                .contains("model_diff")
        );
    }

    #[test]
    fn test_convert_noop() {
        let mat = Material {
            name: String::from("h"),
            material_version: 4,
            data: MaterialData::Hogan(Box::new(HoganMaterialData {
                shader_permutations: vec![],
                ufx_version: 9,
                blend_mode: 0,
                shadow_requires_consts: false,
                skinned: false,
                terrain_blending: false,
                vs_cb_data: Vec::new(),
                ps_cb_data: Vec::new(),
                hs_cb_data: Vec::new(),
                ds_cb_data: Vec::new(),
                gs_cb_data: Vec::new(),
                textures: String::from("x"),
            })),
        };
        let result = convert_material(&mat, true, false);
        assert!(result.is_hogan());
        assert_eq!(result.hogan().unwrap().textures, "x");
    }

    #[test]
    fn test_parse_textures_multiple_types() {
        let parsed = parse_textures_string("m_diff.ddx;m_norm.ddx;m_spec.ddx;m_em.ddx");
        assert!(parsed.diffuse.is_some());
        assert!(parsed.normal.is_some());
        assert!(parsed.gloss.is_some());
        assert!(parsed.emissive.is_some());
    }

    #[test]
    fn test_strip_suffix_ci() {
        assert_eq!(strip_suffix_ci("foo_Diff", "_diff"), Some("foo"));
        assert_eq!(strip_suffix_ci("foo_DIFF", "_diff"), Some("foo"));
        assert_eq!(strip_suffix_ci("foo_bar", "_diff"), None);
        assert_eq!(strip_suffix_ci("x", "_diff"), None);
    }

    #[test]
    fn test_select_perm_set_base_pbr() {
        // Diffuse+Normal+Gloss → Base PBR (index 5, 4-slot, most frequent)
        let needed = &[
            "Albedo_Map",
            "BRDF_Parameter_Map",
            "Normal_Map",
            "Specular_Reflectance",
        ];
        let idx = select_standard_perm_set(needed);
        assert_eq!(HOGAN_STANDARD_PERM_SETS[idx].len(), 4);
        // Should be a base PBR set (no Sand/Emissive)
        let tex = HOGAN_STANDARD_PERM_TEXTURES[idx];
        assert!(!tex.contains(&"Sand_Map"));
        assert!(!tex.contains(&"Emissive_Map"));
    }

    #[test]
    fn test_select_perm_set_emissive() {
        // Diffuse+Normal+Gloss+Emissive → Base PBR + Emissive (index 10)
        let needed = &[
            "Albedo_Map",
            "BRDF_Parameter_Map",
            "Emissive_Map",
            "Normal_Map",
            "Specular_Reflectance",
        ];
        let idx = select_standard_perm_set(needed);
        let tex = HOGAN_STANDARD_PERM_TEXTURES[idx];
        assert!(tex.contains(&"Emissive_Map"));
    }

    #[test]
    fn test_select_perm_set_albedo_only_fallback() {
        // Albedo only → no exact match, falls back to base PBR (smallest superset)
        let needed = &["Albedo_Map"];
        let idx = select_standard_perm_set(needed);
        assert!(HOGAN_STANDARD_PERM_TEXTURES[idx].contains(&"Albedo_Map"));
    }

    #[test]
    fn test_needed_hogan_textures_diffuse_normal_gloss() {
        let mut legacy = LegacyMaterialData::default();
        legacy.maps[MapType::Diffuse as usize] = vec![Map {
            name: String::from("tex_diff.ddx"),
            channel: 0,
            flags: 7,
        }];
        legacy.maps[MapType::Normal as usize] = vec![Map {
            name: String::from("tex_norm.ddx"),
            channel: 0,
            flags: 7,
        }];
        legacy.maps[MapType::Gloss as usize] = vec![Map {
            name: String::from("tex_spec.ddx"),
            channel: 0,
            flags: 7,
        }];
        let needed = needed_hogan_textures(&legacy);
        assert!(needed.contains(&"Albedo_Map"));
        assert!(needed.contains(&"Normal_Map"));
        assert!(needed.contains(&"BRDF_Parameter_Map"));
        assert!(needed.contains(&"Specular_Reflectance"));
    }

    #[test]
    fn test_needed_hogan_textures_auto_adds_brdf() {
        // Diffuse+Normal without Gloss should still get BRDF+Specular
        let mut legacy = LegacyMaterialData::default();
        legacy.maps[MapType::Diffuse as usize] = vec![Map {
            name: String::from("tex_diff.ddx"),
            channel: 0,
            flags: 7,
        }];
        legacy.maps[MapType::Normal as usize] = vec![Map {
            name: String::from("tex_norm.ddx"),
            channel: 0,
            flags: 7,
        }];
        let needed = needed_hogan_textures(&legacy);
        assert!(needed.contains(&"BRDF_Parameter_Map"));
        assert!(needed.contains(&"Specular_Reflectance"));
    }

    #[test]
    fn test_legacy_to_hogan_emissive_selects_right_perm() {
        let mut legacy = LegacyMaterialData::default();
        legacy.maps[MapType::Diffuse as usize] = vec![Map {
            name: String::from("unit_diff.ddx"),
            channel: 0,
            flags: 7,
        }];
        legacy.maps[MapType::Normal as usize] = vec![Map {
            name: String::from("unit_norm.ddx"),
            channel: 0,
            flags: 7,
        }];
        legacy.maps[MapType::Emissive as usize] = vec![Map {
            name: String::from("unit_em.ddx"),
            channel: 0,
            flags: 7,
        }];
        let hogan = legacy_to_hogan(&legacy, false);
        // Should pick the emissive perm set
        assert!(!hogan.shader_permutations.is_empty());
        // The permutation name should come from perm set 10 (emissive)
        let first_name = &hogan.shader_permutations[0].name;
        assert!(
            first_name.starts_with("HOGAN_STANDARD_"),
            "Expected HOGAN_STANDARD permutation, got: {first_name}"
        );
    }

    #[test]
    fn test_legacy_to_hogan_skinned_flag() {
        let mut legacy = LegacyMaterialData::default();
        legacy.maps[MapType::Diffuse as usize] = vec![Map {
            name: String::from("unit_diff.ddx"),
            channel: 0,
            flags: 7,
        }];
        let hogan_static = legacy_to_hogan(&legacy, false);
        assert!(!hogan_static.skinned);
        let hogan_skinned = legacy_to_hogan(&legacy, true);
        assert!(hogan_skinned.skinned);
    }
}
